### PR TITLE
Metadata: Include GateWidth, GratingBlaze

### PR DESCRIPTION
**Pull request by mruijzendaal**
Partially implement #33: gate width (in nanoseconds) and gratingblaze (in m)

### CODE REVIEW

**Comment by fujiisoup** [comment]
@mruijzendaal Thank you for your contribution. This is a good addition.
Could you add a test for this?

It would be great if you could add similar test like this
https://github.com/fujiisoup/sif_parser/blob/c955a584ac009cbaf0e280bdb402f1cc92dd1dd5/testings/test_open.py#L46-L50

**Comment by fujiisoup** [comment]
image
It seems that this is incompatible to some files... I am going to take a look, but it would be appreciated if you could also work for this.

**Comment by mruijzendaal** [comment]
I'll make the necessary changes. It appears I made some mistake in reading through the metadata lines.
On a related note: is there a specific reason that something like `_to_string(fp.readline().split())` isn't used more often, instead of the `_read_until(fp, ' ')` ?

**Comment by mruijzendaal** [comment]
I added a test for issue #33 that checks if the parsed metadata agrees with Andor's values. Apologies for my autoformatter changing the `_sif_open.py` file a lot. I can revert these changes if you prefer.

**Comment by fujiisoup** [comment]
Thank you for your work. 
(I fixed small bugs, but) it is being merged.

> is there a specific reason that something like _to_string(fp.readline().split()) isn't used more often, instead of the _read_until(fp, ' ') ?

No reason. Probably I did not know what it means or I did not have a time to implement.
I added an issue #35.
It would be appreciated if you could help us implementing more metadata.

**Pull request merged**
